//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freshproject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINUX
    {
        public int ID { get; set; }
        public string REGNO { get; set; }
        public string RANK { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public string THEORY { get; set; }
        public string PRACTICAL { get; set; }
        public string G_TOTAL { get; set; }
        public string GRADING { get; set; }
        public string REMARKS { get; set; }
        public string BATCHRANK { get; set; }
    }
}
